/**
 * Shellwork breed catalog — hen ↔ egg pairs for the color scene.
 * Sources: Koops Coops weekly hatch list, Murray McMurray 2026 catalog,
 * Cackle Hatchery breed chart + egg-color article (Gail Damerow).
 */
export const EGG_FAMILIES = [
  { id: 'white', label: 'White', short: 'White' },
  { id: 'tinted', label: 'Tinted', short: 'Tint' },
  { id: 'brown', label: 'Brown', short: 'Brown' },
  { id: 'dark', label: 'Dark chocolate', short: 'Dark' },
  { id: 'blue', label: 'Blue', short: 'Blue' },
  { id: 'olive', label: 'Green / olive', short: 'Olive' },
];

export const EGG_SHELL_STYLE = {
  white: { bg: 'linear-gradient(145deg,#fffef9,#e7dfd2)', speckled: false },
  tinted: { bg: 'linear-gradient(145deg,#f7e7c8,#e2c08a)', speckled: false },
  brown: { bg: 'linear-gradient(145deg,#c9956a,#8a5330)', speckled: true },
  dark: { bg: 'linear-gradient(145deg,#6b3a28,#2c1810)', speckled: true },
  blue: { bg: 'linear-gradient(145deg,#b7d6d8,#5a9399)', speckled: false },
  olive: { bg: 'linear-gradient(145deg,#9aaa6e,#556334)', speckled: true },
};

var SRC = {
  koops: { label: 'Koops Coops', url: 'https://www.koopscoops.com/' },
  koopsProcess: { label: 'Koops Coops hatch list', url: 'https://www.koopscoops.com/process/' },
  mcmurray: { label: 'Murray McMurray Hatchery', url: 'https://www.mcmurrayhatchery.com/' },
  mcmurrayCat: { label: 'McMurray 2026 catalog', url: 'https://www.mcmurrayhatchery.com/mmhcat.html' },
  cackleBreeds: { label: 'Cackle Hatchery breed chart', url: 'https://www.cacklehatchery.com/chicken-breeds/' },
  cackleColor: { label: 'Cackle — egg colors (Damerow)', url: 'https://www.cacklehatchery.com/why-do-chicken-eggs-come-in-different-colors/' },
};

export const BREEDS = [
  {
    id: 'leghorn',
    name: 'White Leghorn',
    eggColorFamily: 'white',
    eggColorLabel: 'White',
    eggSize: 'Large to Extra Large',
    henTraits: {
      comb: 'Tall bright-red single comb; neat red wattles.',
      plumage: 'Sleek pure white; tight feathering.',
      body: 'Light, upright, alert — built to lay, not bulk.',
      legs: 'Clean yellow shanks; white earlobes (classic white-egg cue).',
    },
    tagline: 'Mediterranean layer',
    simpleCopy: 'No brown or blue pigment is deposited, so the calcium shell reads chalk-white. According to Cackle Hatchery, most supermarket white eggs come from Leghorn hens, and Mediterranean breeds as a class lay white shells.',
    advancedCopy: 'White earlobes correlate strongly (not perfectly) with white eggs in Mediterranean breeds. Absence of protoporphyrin and biliverdin leaves an untinted calcite shell. McMurray lists Pearl White Leghorns among its top white-egg production birds; Cackle rates White Leghorns at 220–300 Large–XL white eggs per year.',
    photo: 'images/breed-leghorn.jpg',
    photoCredit: 'Photo: Stephen Ausmus, USDA ARS, public domain',
    sources: [SRC.cackleColor, SRC.cackleBreeds, SRC.mcmurrayCat, SRC.koopsProcess],
  },
  {
    id: 'ancona',
    name: 'Ancona',
    eggColorFamily: 'white',
    eggColorLabel: 'White',
    eggSize: 'Medium',
    henTraits: {
      comb: 'Bright red single comb (protect in hard freezes).',
      plumage: 'Lustrous black with white-tipped mottling.',
      body: 'Quick, alert Mediterranean forager; prefers open range.',
      legs: 'Clean yellow shanks; white earlobes.',
    },
    tagline: 'Mottled Mediterranean layer',
    simpleCopy: 'Anconas lay medium white eggs. According to Murray McMurray Hatchery, they are excellent foragers whose dark mottled pattern helps in hawk country, and hens are generally non-setters.',
    advancedCopy: 'APA Mediterranean class; McMurray notes good white-egg production with a Watch status on The Livestock Conservancy list. White earlobes and white shells track the Mediterranean pattern Cackle describes for the class.',
    photo: 'images/breed-ancona.jpg',
    photoCredit: 'Photo: Uikitireza, CC BY-SA 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Poule_Anc%C3%B4ne_noir_caillout%C3%A9_blanc_GR.jpg',
    sources: [SRC.mcmurrayCat, SRC.cackleColor],
  },
  {
    id: 'minorca',
    name: 'Black Minorca',
    eggColorFamily: 'white',
    eggColorLabel: 'White',
    eggSize: 'Extra Large',
    henTraits: {
      comb: 'Very large red single comb and long wattles.',
      plumage: 'Glossy black with a swooping tail.',
      body: 'Largest Mediterranean type — long, muscular frame.',
      legs: 'Clean slate shanks; large white earlobes.',
    },
    tagline: 'Heat-tolerant white-egg giant',
    simpleCopy: 'Minorcas are famous for oversized white eggs. According to Cackle Hatchery, Black Minorcas are excellent Extra Large white layers and strong heat-hardy birds.',
    advancedCopy: 'McMurray recounts founder Murray McMurray winning a 1917 Iowa State Fair blue ribbon with a Black Minorca — and still lists them as good white layers that prefer warm free-range conditions. Cackle marks them Non-setter with Extra Large white shells.',
    photo: 'images/breed-minorca.jpg',
    photoCredit: 'Photo: Spaarnestad Photo (photographer unknown), public domain, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Kip_(zwarte_minorca_hen)_op_pluimveetentoonstelling_(van_de_Amsterdamse_Pluimvee_Club)_in_Amsterdam,_SFA022806240.jpg',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat, SRC.cackleColor],
  },
  {
    id: 'polish',
    name: 'Polish',
    eggColorFamily: 'white',
    eggColorLabel: 'White',
    eggSize: 'Medium',
    henTraits: {
      comb: 'Small V-comb nearly hidden under the crest.',
      plumage: 'Dramatic crest (e.g. white-crested black); ornamental outline.',
      body: 'Light crested ornamental; limited forward vision from the topknot.',
      legs: 'Clean shanks; typically white or slate depending on variety.',
    },
    tagline: 'Crested ornamental layer',
    simpleCopy: 'Polish hens lay white eggs and wear a showy crest. Koops Coops lists Polish on the weekly hatch plan; Cackle charts Buff Laced, Golden Laced, and White Crested Polish as white-egg birds.',
    advancedCopy: 'According to Cackle, Polish varieties are Poor cold hardy, Non-setters, and white-egg layers — crest care and predator awareness matter more than shell color genetics. McMurray groups Polish with other “top hat” breeds in the catalog.',
    photo: 'images/breed-polish.jpg',
    photoCredit: 'Photo: Wildcarno, CC0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:White_crested_polish_hen.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'silkie',
    name: 'Silkie',
    eggColorFamily: 'tinted',
    eggColorLabel: 'Cream / tinted',
    eggSize: 'Small (bantam)',
    henTraits: {
      comb: 'Walnut comb; turquoise-blue earlobes are a Silkie hallmark.',
      plumage: 'Fur-like fluffy feathers; often bearded and crested.',
      body: 'Small, cuddly ornamental; famously broody mothers.',
      legs: 'Feathered five-toed feet; soft outline from head to toe.',
    },
    tagline: 'Fluffy pet & setter',
    simpleCopy: 'Silkies lay small cream or tinted eggs and love to sit. According to Cackle Hatchery, Silkie bantams lay cream or tinted shells and are strong setters; Koops Coops hatches Silkies weekly.',
    advancedCopy: 'Cackle’s egg-color article notes Silkies (and some Sebrights) can show turquoise earlobes while still laying white or slightly tinted off-white shells — an exception to the red/white earlobe rule of thumb. Treat them as ornamental layers, not production birds.',
    photo: 'images/breed-silkie.jpg',
    photoCredit: 'Photo: Frank Vincentz, CC BY-SA 3.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Kluse_-_Silkie_Bantam_hen_04_ies.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurrayCat],
  },
  {
    id: 'hamburg',
    name: 'Silver Spangled Hamburg',
    eggColorFamily: 'white',
    eggColorLabel: 'White',
    eggSize: 'Medium',
    henTraits: {
      comb: 'Bright red rose comb.',
      plumage: 'Silver-white with black spangles on each feather tip.',
      body: 'Small, elegant, flighty forager — the “Dutch Everyday Layer.”',
      legs: 'Clean gray-blue shanks; white earlobes.',
    },
    tagline: 'Spangled white-egg flyer',
    simpleCopy: 'Hamburgs are prolific white-egg layers in a small package. According to Murray McMurray Hatchery, Silver Spangled Hamburgs are consistent white layers that thrive when free-ranging.',
    advancedCopy: 'McMurray places Hamburgs on The Livestock Conservancy Threatened list and notes the historic “Dutch Everyday Layer” reputation. Cackle lists Silver Spangled Hamburg at 200+ medium white eggs per year.',
    photo: 'images/breed-hamburg.jpg',
    photoCredit: 'Photo: Jay & Melissa Malouin from North Hampton, USA, CC BY-SA 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Silver_Spangled_Hen.jpg',
    sources: [SRC.mcmurrayCat, SRC.cackleBreeds, SRC.cackleColor],
  },
  {
    id: 'orpington',
    name: 'Buff Orpington',
    eggColorFamily: 'tinted',
    eggColorLabel: 'Light brown / tinted',
    eggSize: 'Large',
    henTraits: {
      comb: 'Medium red single comb; soft red wattles.',
      plumage: 'Dense warm buff; fluffy outline.',
      body: 'Broad, low, broody-looking; calm carriage.',
      legs: 'Sturdy clean shanks tucked under a heavy frame.',
    },
    tagline: 'Heavy dual-purpose',
    simpleCopy: 'Buff Orpingtons lay light brown or cream “tinted” eggs and make gentle backyard pets. According to Cackle Hatchery they produce 200–280 Large brown eggs yearly and are Very cold- and heat-hardy; Koops Coops hatches Buff Orpingtons weekly.',
    advancedCopy: 'Tinted shells carry a lighter load of protoporphyrin than dark brown layers. McMurray highlights Orpingtons as beginner-friendly Heritage birds with sweet personalities. Homesteaders often see Large–XL eggs once hens mature.',
    photo: 'images/breed-orpington.jpg',
    photoCredit: 'Photo: Pexels, Pexels License',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat, SRC.cackleColor],
  },
  {
    id: 'lavender-orpington',
    name: 'Lavender Orpington',
    eggColorFamily: 'tinted',
    eggColorLabel: 'Light brown',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Soft lavender-blue self color on a fluffy Orpington frame.',
      body: 'Heavy, calm dual-purpose type like other Orpingtons.',
      legs: 'Clean shanks; quiet backyard presence.',
    },
    tagline: 'Lavender dual-purpose',
    simpleCopy: 'Lavender Orpingtons keep the Orpington temperament with pastel plumage and light brown eggs. Koops Coops lists Lavender Orpingtons on the weekly hatch plan; Cackle charts them as Medium brown-egg layers.',
    advancedCopy: 'According to Cackle, Lavender Orpingtons are Very cold hardy, Good heat hardy, and frequent setters. Egg color sits in the tinted-to-light-brown band — not dark chocolate — matching other Orpington varieties.',
    photo: 'images/breed-lavender-orpington.jpg',
    photoCredit: 'Photo: Idéalités, CC BY-SA 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Orpington_lavande.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'mottled-orpington',
    name: 'Mottled English Orpington',
    eggColorFamily: 'tinted',
    eggColorLabel: 'Light brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Mottled black-and-white English Orpington pattern.',
      body: 'Heavy, fluffy dual-purpose frame.',
      legs: 'Clean sturdy shanks.',
    },
    tagline: 'Mottled English dual-purpose',
    simpleCopy: 'Mottled English Orpingtons lay light brown eggs on a heavy fluffy frame. According to Koops Coops they appear on the weekly hatch list alongside Buff and Lavender Orpingtons.',
    advancedCopy: 'Shell color follows the Orpington tinted/light-brown pattern Cackle documents for Buff Orpingtons (Large brown). Treat mottling as plumage variety, not a separate pigment story for the egg.',
    photo: null,
    photoCredit: null,
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurray],
  },
  {
    id: 'faverolles',
    name: 'Salmon Faverolles',
    eggColorFamily: 'tinted',
    eggColorLabel: 'Cream / light brown',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Small single comb framed by beard and muffs.',
      plumage: 'Creamy salmon hens; darker cream/red/black males.',
      body: 'Feather-legged French dual-purpose with a fifth toe.',
      legs: 'Lightly feathered shanks; white skin.',
    },
    tagline: 'Bearded feather-leg',
    simpleCopy: 'Salmon Faverolles lay cream to light brown eggs and look like living teddy bears. Koops Coops hatches them weekly; McMurray calls them gentle, confinement-friendly birds that lay medium cream eggs.',
    advancedCopy: 'According to Cackle Hatchery, Salmon Faverolles lay Medium–Large light brown eggs (180–240/year) and are Good cold hardy. McMurray notes high broodiness — great mothers, not always the most continuous layers.',
    photo: 'images/breed-faverolles.jpg',
    photoCredit: 'Photo: stephen jones from uk, CC BY 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Salmon_Faverolles_cock_and_hen_(cropped).jpg',
    photoAlt: 'Salmon Faverolles rooster and hen',
    sources: [SRC.koopsProcess, SRC.mcmurrayCat, SRC.cackleBreeds],
  },
  {
    id: 'sussex',
    name: 'Speckled Sussex',
    eggColorFamily: 'tinted',
    eggColorLabel: 'Light brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Mahogany base with white speckles that increase with each molt.',
      body: 'Friendly English dual-purpose; excellent forager.',
      legs: 'Clean pinkish-white shanks.',
    },
    tagline: 'Speckled English dual-purpose',
    simpleCopy: 'Speckled Sussex hens lay large light brown eggs and pepper their plumage with more white each year. According to Cackle they are Very cold hardy Large light-brown layers; Koops Coops lists them on the weekly hatch plan.',
    advancedCopy: 'McMurray praises Speckled Sussex as friendly English-class birds that do well in mixed flocks. Cackle charts 180–240 Large light brown eggs per year with setter tendency.',
    photo: 'images/breed-sussex.jpg',
    photoCredit: 'Photo: Davee, CC BY 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Speckled_Sussex_Chicken.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'rir',
    name: 'Rhode Island Red',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Bright red single comb with clear points; matching wattles.',
      plumage: 'Rich mahogany to golden-brown; dense layered feathers.',
      body: 'Medium, plump, purposeful stride on pasture.',
      legs: 'Clean yellowish shanks; red earlobes (brown-egg cue).',
    },
    tagline: 'American dual-purpose',
    simpleCopy: 'Rhode Island Reds wear brown pigment on the outer shell. According to Cackle Hatchery they lay 200–280 Large brown eggs yearly and handle both cold and heat well; Koops Coops hatches RI Reds every week.',
    advancedCopy: 'Protoporphyrin IX is deposited late in the shell gland, mostly on cuticle and outer calcite — which is why brown can rub slightly. McMurray catalogs Rhode Island Reds among core brown-egg Heritage layers. Red earlobes track with brown eggs in many (not all) breeds, as Cackle’s Damerow article explains.',
    photo: 'images/breed-rir.jpg',
    photoCredit: 'Photo: Unsplash, Unsplash License',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat, SRC.cackleColor],
  },
  {
    id: 'barred-rock',
    name: 'Barred Plymouth Rock',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Classic black-and-white barring (“cuckoo” look).',
      body: 'Sturdy American dual-purpose; calm backyard manners.',
      legs: 'Clean yellow shanks; red earlobes.',
    },
    tagline: 'Barred American classic',
    simpleCopy: 'Barred Rocks lay plenty of large brown eggs and wear zebra plumage. According to Cackle they produce 200–280 Large brown eggs and are Very cold- and heat-hardy; Koops Coops lists Barred Rocks on the weekly hatch plan.',
    advancedCopy: 'McMurray treats Plymouth Rocks as foundational brown-egg Heritage stock and beginner-friendly. Barring is plumage genetics separate from shell pigment — both sexes show the zebra pattern, with males often reading lighter.',
    photo: 'images/breed-barred-rock.jpg',
    photoCredit: 'Photo: Thomas Kriese, CC BY 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Barred_Rock_hen_in_backyard.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'australorp',
    name: 'Black Australorp',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Large bright-red single comb.',
      plumage: 'Glossy black with greenish-purple sheen.',
      body: 'Quiet, gentle dual-purpose; soft English-class manners.',
      legs: 'Clean dark (black) shanks.',
    },
    tagline: 'Australian utility layer',
    simpleCopy: 'Black Australorps are brown-egg powerhouses with glossy black plumage. According to Cackle Hatchery they lay 200–280 Large brown eggs and are Very hardy; McMurray notes a historic 364-eggs-in-365-days record bird.',
    advancedCopy: 'McMurray reports Australorps graduated from The Livestock Conservancy Priority List in 2023 after conservation success. Koops Coops lists Black Australorps (and Blue) on the weekly hatch plan. Shell color is standard brown — not dark chocolate.',
    photo: 'images/breed-australorp.jpg',
    photoCredit: 'Photo: Thomon, CC BY-SA 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Poule_australorp_noire.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'blue-australorp',
    name: 'Blue Australorp',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Large bright-red single comb.',
      plumage: 'Slate-blue body (splash/black siblings appear from blue genetics).',
      body: 'Same calm dual-purpose type as Black Australorps.',
      legs: 'Clean dark shanks.',
    },
    tagline: 'Blue-plumage utility layer',
    simpleCopy: 'Blue Australorps lay the same brown eggs as Blacks — the “blue” is feather color, not shell color. Koops Coops lists Blue Australorps on the weekly hatch plan alongside Blacks.',
    advancedCopy: 'Blue plumage genetics typically yield ~50% blue chicks from blue×blue matings, with black and splash siblings — the same pattern McMurray explains for blue-feathered poultry. Egg pigment remains brown protoporphyrin on the outer shell.',
    photo: 'images/breed-blue-australorp.jpg',
    photoCredit: 'Photo: Arie M. den Toom, CC BY-SA 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Auustralorp_blauw_gezoomd_26_w.jpg',
    sources: [SRC.koopsProcess, SRC.mcmurrayCat, SRC.cackleBreeds],
  },
  {
    id: 'wyandotte',
    name: 'Silver Laced Wyandotte',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Medium',
    henTraits: {
      comb: 'Rose comb (cold-hardy advantage).',
      plumage: 'Silver-white feathers with black lacing.',
      body: 'Compact, rounded American dual-purpose.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'Laced rose-comb classic',
    simpleCopy: 'Laced Wyandottes lay medium brown eggs under rose combs and laced coats. Koops Coops lists Laced Wyandottes weekly; Cackle charts Silver Laced Wyandottes at 180–260 Medium brown eggs with Very cold hardiness.',
    advancedCopy: 'McMurray catalogs multiple Wyandotte lace colors (silver, golden, blue laced red). Rose combs resist frostbite better than large singles — a practical cold-climate trait separate from shell color.',
    photo: 'images/breed-wyandotte.jpg',
    photoCredit: 'Photo: Holly from asheville, usa, CC BY 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Silver_Laced_trio.jpg',
    photoAlt: 'Three Silver Laced Wyandotte hens',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'new-hampshire',
    name: 'New Hampshire',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large to Extra Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Lighter, brighter red than Rhode Island Reds; fast-feathering.',
      body: 'Dual-purpose American; stronger meat frame than production reds.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'Fast-maturing dual-purpose',
    simpleCopy: 'New Hampshires lay large brown eggs and grow out quickly. According to Cackle they produce 200–280 Large–XL brown eggs; McMurray notes they were selected from Rhode Island Reds for vigor and brown-egg size.',
    advancedCopy: 'McMurray places New Hampshires as Threatened on The Livestock Conservancy list despite their broiler-industry history. Shell color is standard brown — a productive dual-purpose band rather than dark chocolate.',
    photo: 'images/breed-new-hampshire.jpg',
    photoCredit: 'Photo: Bodlina, CC BY-SA 3.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:New_Hampshire_Red_Hen.jpg',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'brahma',
    name: 'Light Brahma',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Small pea comb — excellent in cold weather.',
      plumage: 'Silver-white with black-edged hackles and black tail.',
      body: 'Massive Asiatic dual-purpose; slow to fully mature.',
      legs: 'Heavily feathered yellow shanks and feet.',
    },
    tagline: 'Feather-footed gentle giant',
    simpleCopy: 'Light Brahmas lay medium-to-large brown eggs and shrug off winter. According to Cackle they are Very cold- and heat-hardy brown layers; McMurray praises their winter laying and family-friendly manners.',
    advancedCopy: 'McMurray notes Light Brahmas as the best layers among Buff/Dark/Light varieties (~220 eggs/year) and APA Heritage birds that graduated Conservancy listing in 2023. Pea comb + feathered legs = cold-climate package.',
    photo: 'images/breed-brahma.jpg',
    photoCredit: 'Photo: Drcbrothephotographer, CC BY 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Light_Brahma_(maybe_bantam)_hen_in_Gyeongju_2025-01-15.jpg',
    photoAlt: 'Light Brahma hen',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'cochin',
    name: 'Buff Cochin',
    eggColorFamily: 'brown',
    eggColorLabel: 'Light brown',
    eggSize: 'Medium',
    henTraits: {
      comb: 'Small-to-medium single comb nestled in fluff.',
      plumage: 'Immense soft buff feathers from head to toe.',
      body: 'Round “walking pillow”; calm, broody mothers.',
      legs: 'Fully feathered yellow feet — classic Asiatic pantaloons.',
    },
    tagline: 'Fluffy Asiatic setter',
    simpleCopy: 'Buff Cochins lay medium light brown eggs and go broody often. Koops Coops lists Cochins on the weekly hatch plan; Cackle charts Buff Cochin Standards at 110–160 Medium brown eggs with Very cold hardiness.',
    advancedCopy: 'McMurray calls Cochins perfect for first-time keepers and natural hatching — excellent mothers more than peak production. Shell color is light-to-medium brown; the breed’s fame is fluff and temperament.',
    photo: 'images/breed-cochin.jpg',
    photoCredit: 'Photo: Benoit Brummer (Trougnouf), CC BY 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Cochin_fauve_%C3%A0_Auderghem_(DSCF6331).jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'jersey-giant',
    name: 'Black Jersey Giant',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Straight red single comb (watch frostbite).',
      plumage: 'Black with green sheen; immense outline.',
      body: 'Largest American chicken — slow-growing dual-purpose.',
      legs: 'Clean black shanks and toes.',
    },
    tagline: 'American heavy dual-purpose',
    simpleCopy: 'Jersey Giants lay large brown eggs on the biggest American frames. According to Cackle, Black Jersey Giants produce 180–260 Medium brown eggs and are Very cold hardy.',
    advancedCopy: 'McMurray notes Giants are Recovering on The Livestock Conservancy list, strong winter layers, and better suited to cool climates than hot ones. Egg color is ordinary brown — size of bird ≠ darkness of shell.',
    photo: 'images/breed-jersey-giant.jpg',
    photoCredit: 'Photo: Uikitireza, CC BY-SA 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Poule_G%C3%A9ante_de_Jersey_1.jpg',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'dominique',
    name: 'Dominique',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Rose comb on a medium American frame.',
      plumage: 'Black-and-white barring (finer than Barred Rock).',
      body: 'Historic New England dual-purpose; friendly forager.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'America’s oldest breed',
    simpleCopy: 'Dominiques lay large brown eggs under rose combs and barred coats. According to Cackle they produce 180–260 Medium brown eggs; McMurray calls them a distinctly American Heritage bird and APA Certified flock.',
    advancedCopy: 'McMurray notes Dominiques predate Plymouth Rocks and sit at Conservancy Watch status. Rose comb + barring distinguish them from single-comb Barred Rocks at a glance.',
    photo: 'images/breed-dominique.jpg',
    photoCredit: 'Photo: gunthercox, CC0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Dominique_chicken.JPG',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'delaware',
    name: 'Delaware',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large to Extra Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Mostly white with slight barring on hackles and tail.',
      body: 'American dual-purpose from mid-century broiler roots.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'Light-feathered dual-purpose',
    simpleCopy: 'Delawares lay large brown eggs on mostly white bodies. According to Cackle they produce 180–260 Large–XL brown eggs; McMurray highlights cold hardiness and solid winter laying.',
    advancedCopy: 'McMurray traces Delawares to Barred Rock × New Hampshire broiler work in Delaware and lists them Recovering on Conservancy lists. Shell color stays in the standard brown band.',
    photo: 'images/breed-delaware.jpg',
    photoCredit: 'Photo: Josh Larios from Seattle, US, CC BY-SA 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Delaware_pullet_in_foreground.jpg',
    photoAlt: 'Delaware pullet',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'java',
    name: 'Mottled Java',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Black with white mottling (also Black and White Java varieties).',
      body: 'One of America’s oldest breeds; long-backed dual-purpose.',
      legs: 'Clean dark shanks.',
    },
    tagline: 'Historic American dual-purpose',
    simpleCopy: 'Mottled Javas lay brown eggs on an old American dual-purpose frame. Koops Coops lists Mottled Java on the weekly hatch plan among Heritage favorites.',
    advancedCopy: 'Javas are Livestock Conservancy priority birds historically — treat hatchery notes as availability signals and Conservancy pages for conservation context. Egg color is brown, not blue or olive.',
    photo: 'images/breed-java.jpg',
    photoCredit: 'Photo (Black variety): Uikitireza, CC BY-SA 4.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Poule_Java_noire.jpg',
    photoAlt: 'Black Java hen',
    sources: [SRC.koopsProcess, SRC.mcmurray, SRC.cackleBreeds],
  },
  {
    id: 'naked-neck',
    name: 'Naked Neck (Turken)',
    eggColorFamily: 'brown',
    eggColorLabel: 'Light brown',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Red single comb on a bare red neck.',
      plumage: 'Mixed colors; distinctive featherless neck (not a turkey hybrid).',
      body: 'Heat-tolerant dual-purpose; calm mixed-flock manners.',
      legs: 'Clean shanks; sparse neck skin shows bright red.',
    },
    tagline: 'Bare-neck brown layer',
    simpleCopy: 'Naked Necks lay light brown eggs and handle heat with less neck feathering. According to Cackle they produce 180–240 Medium–Large light brown eggs and are Very heat hardy.',
    advancedCopy: 'McMurray notes Naked Necks as excellent brown layers (including many double-yolkers in their flock) with broody mothering. The bare neck is a genetic trait (Na), not a turkey cross despite the “Turken” nickname.',
    photo: 'images/breed-naked-neck.jpg',
    photoCredit: 'Photo: Simone Ramella from Rome, Italy, CC BY 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Naked_Neck_hens_-_Italy.jpg',
    photoAlt: 'Naked Neck hens',
    sources: [SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'mystic-onyx',
    name: 'Mystic Onyx',
    eggColorFamily: 'brown',
    eggColorLabel: 'Brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Typically a pea or small comb on dark-faced birds.',
      plumage: 'Near-black ornamental “onyx” look popular in fancy flocks.',
      body: 'Hybrid/fancy dual-purpose type — not an APA closed breed.',
      legs: 'Often dark shanks matching the black plumage package.',
    },
    tagline: 'Black fancy hybrid',
    simpleCopy: 'Mystic Onyx birds are black-plumage fancy layers that typically lay brown eggs. Koops Coops lists Mystic Onyx on the weekly hatch plan among ornamental producers.',
    advancedCopy: 'Unlike closed APA breeds, Mystic Onyx is a hatchery/fancy trade name — expect variation. Shell color is generally brown; do not confuse black plumage with chocolate egg genetics (those track Marans/Welsummer/Penedesenca lines).',
    photo: null,
    photoCredit: null,
    sources: [SRC.koopsProcess, SRC.mcmurray, SRC.cackleBreeds],
  },
  {
    id: 'black-copper-marans',
    name: 'Black Copper Marans',
    eggColorFamily: 'dark',
    eggColorLabel: 'Dark chocolate brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Large red single comb (frostbite watch).',
      plumage: 'Deep black hens with copper neck flecks; copper-hackled roosters.',
      body: 'French dual-purpose; often lightly feathered shanks.',
      legs: 'Feathered slate shanks on French type; pinkish-white on some English lines.',
    },
    tagline: 'Chocolate-egg French classic',
    simpleCopy: 'Black Copper Marans are the poster birds for dark chocolate eggs. According to Cackle Hatchery, French Black Copper Marans lay Large dark brown eggs; Koops Coops hatches Black Copper Marans weekly.',
    advancedCopy: 'Cackle’s Damerow article lists Marans among breeds with the darkest shells (with Barnevelders, Penedesencas, and Welsummers). McMurray stresses egg color as the defining breeding priority. Brown pigment sits on the outside — the interior of a cracked dark shell still looks white.',
    photo: 'images/breed-black-copper-marans.jpg',
    photoCredit: 'Photo: Nienetwiler, CC BY 2.5 CH, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Maranshenne-Kupferschwarz.jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurrayCat],
  },
  {
    id: 'blue-copper-marans',
    name: 'Blue Copper Marans',
    eggColorFamily: 'dark',
    eggColorLabel: 'Dark chocolate brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Large red single comb.',
      plumage: 'Blue/slate body with copper neck highlights (plus black/splash siblings).',
      body: 'Same Marans dual-purpose type as Black Copper.',
      legs: 'Often lightly feathered slate shanks on French lines.',
    },
    tagline: 'Blue-plumage chocolate layer',
    simpleCopy: 'Blue Copper Marans lay the same dark chocolate eggs — “blue” is feather genetics. Koops Coops lists Blue Copper Marans on the weekly hatch plan beside Black Copper.',
    advancedCopy: 'Shell darkness comes from heavy protoporphyrin deposition, not plumage color. Pairing blue Marans still aims at dark eggs; McMurray and Cackle both treat Marans egg color as the primary selection trait.',
    photo: 'images/breed-blue-copper-marans.jpg',
    photoCredit: 'Photo: ThomasHoemske, CC BY-SA 3.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Marans_blau-kupfer.jpg',
    photoAlt: 'Blue Copper Marans rooster',
    sources: [SRC.koopsProcess, SRC.cackleColor, SRC.mcmurrayCat],
  },
  {
    id: 'welsummer',
    name: 'Welsummer',
    eggColorFamily: 'dark',
    eggColorLabel: 'Dark brown (often terracotta speckled)',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Medium red single comb.',
      plumage: 'Partridge hens; rich red-and-black roosters.',
      body: 'Dutch dual-purpose; active forager.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'Terracotta dark-brown layer',
    simpleCopy: 'Welsummers lay dark brown eggs that often show terracotta speckles. According to Cackle Hatchery they produce 200–280 Medium–Large dark brown eggs; McMurray lists them among rare Heritage dark layers.',
    advancedCopy: 'Cackle’s egg-color article groups Welsummers with Marans and Barnevelders for darkest shells. Speckling is extra surface pigment. Interior of the shell remains white because brown sits on the outside.',
    photo: 'images/breed-welsummer.jpg',
    photoCredit: 'Photo: Josh Larios from Seattle, US, CC BY-SA 2.0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Welsummer_hen.jpg',
    sources: [SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurrayCat],
  },
  {
    id: 'barnevelder',
    name: 'Barnevelder',
    eggColorFamily: 'dark',
    eggColorLabel: 'Dark brown',
    eggSize: 'Large',
    henTraits: {
      comb: 'Bright red single comb and wattles.',
      plumage: 'Double-laced black over reddish-brown (showstopper hens).',
      body: 'Quiet Dutch dual-purpose; slower to mature.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'Double-laced dark layer',
    simpleCopy: 'Barnevelders lay dark brown eggs under beautiful laced feathers. According to Cackle they produce 150–200 Large dark brown eggs; McMurray highlights hardiness and consistent brown lay once mature.',
    advancedCopy: 'Cackle’s Damerow article lists Barnevelders among darkest-shell breeds. McMurray notes they can take longer to start laying than faster Heritage layers — patience for both lace pattern and egg color.',
    photo: 'images/breed-barnevelder.jpg',
    photoCredit: 'Photo: Morgan Leigh, CC BY-SA 2.5, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Barnevelder_hen.jpg',
    sources: [SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurrayCat],
  },
  {
    id: 'ameraucana',
    name: 'Ameraucana',
    eggColorFamily: 'blue',
    eggColorLabel: 'Blue',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Small red pea comb; muffs and beard hide the face line.',
      plumage: 'Many APA colors (here often blue-laced grey); full cheeks.',
      body: 'Medium, sturdy blue-egg standard breed.',
      legs: 'Often slate or greenish; paired with the blue-egg package.',
    },
    tagline: 'Blue-egg standard breed',
    simpleCopy: 'Ameraucanas lay blue eggs tinted by biliverdin in the shell itself. According to Cackle Hatchery, Ameraucanas lay Medium–Large blue (sometimes light green) eggs; McMurray calls them hardy, family-friendly blue layers.',
    advancedCopy: 'Cackle’s Damerow article: blue pigment spreads through the full shell thickness, so the interior stays blue-green. True Ameraucanas follow a breed standard (muffs/beard/pea comb); backyard blue layers without standard type are usually Easter Eggers.',
    photo: 'images/breed-ameraucana.jpg',
    photoCredit: 'Photo: Ameraucana, CC BY-SA, via Wikimedia Commons',
    sources: [SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurrayCat, SRC.koops],
  },
  {
    id: 'cream-legbar',
    name: 'Cream Legbar',
    eggColorFamily: 'blue',
    eggColorLabel: 'Blue / turquoise',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Single comb with a small swept-back crest on hens.',
      plumage: 'Silver-grey hens with salmon breasts; auto-sexing chicks.',
      body: 'Active English-developed layer; temperate to warm climates.',
      legs: 'Clean yellow shanks.',
    },
    tagline: 'Auto-sexing blue layer',
    simpleCopy: 'Cream Legbars lay turquoise-blue eggs and can be sexed by chick color at hatch. Koops Coops hatches Cream Legbars weekly; according to Cackle they lay Medium–Large blue eggs (180–200/year).',
    advancedCopy: 'McMurray describes Crested Cream Legbars as Cambridge-developed auto-sexing birds not yet APA-recognized in the U.S., selected for consistent blue/turquoise shells. Auto-sexing is plumage genetics — separate from the oocyan blue-egg locus.',
    photo: 'images/breed-cream-legbar.jpg',
    photoCredit: 'Photo: Kringln, CC0, via Wikimedia Commons',
    photoSource: 'https://commons.wikimedia.org/wiki/File:Adult_Cream_Legbar_Hen_(cropped).jpg',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
  {
    id: 'easter-egger',
    name: 'Easter Egger',
    eggColorFamily: 'blue',
    eggColorLabel: 'Blue, green, or tinted (variable)',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Often pea or walnut; muffs and beards common.',
      plumage: 'Highly variable — every hatchery’s mix differs.',
      body: 'Mixed Araucana/Ameraucana-derived backyard type.',
      legs: 'Slate, willow, or yellow — not standardized.',
    },
    tagline: 'Mixed colorful layer',
    simpleCopy: 'Easter Eggers are not a closed breed — each hen may lay blue, green, tinted, or brownish eggs. According to Cackle Hatchery they are Multi-color Medium–Large layers; Koops Coops hatches Easter Eggers every week.',
    advancedCopy: 'Cackle’s Damerow article: hatchery Easter Eggers include some blue-shell genetics, so baskets range from blue and green to pinkish, white, or pale yellow/gray. Do not confuse with standard Ameraucanas or rumpless tufted Araucanas.',
    photo: 'images/breed-olive-egger.jpg',
    photoCredit: 'Photo: Easter Egger hen “Gem”, CC BY-SA, via Wikimedia Commons',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurray],
  },
  {
    id: 'araucana',
    name: 'Araucana',
    eggColorFamily: 'blue',
    eggColorLabel: 'Blue',
    eggSize: 'Medium',
    henTraits: {
      comb: 'Pea comb; rumpless; distinctive ear tufts (not muffs).',
      plumage: 'Variable; clean face line with tufts from the ear area.',
      body: 'South American–derived blue-egg breed; rumpless silhouette.',
      legs: 'Often willow or slate clean shanks.',
    },
    tagline: 'Tufted rumpless blue layer',
    simpleCopy: 'True Araucanas lay blue eggs and wear ear tufts on a rumpless body. According to Cackle’s Damerow article, blue shells are characteristic of Araucanas and related Ameraucanas.',
    advancedCopy: 'Biliverdin tints the full shell thickness. Tufts ≠ muffs/beards — Ameraucanas were developed to keep blue eggs while avoiding some Araucana breeding challenges. Backyard “Araucana” labels are often Easter Eggers.',
    photo: 'images/breed-araucana.jpg',
    photoCredit: 'Photo: Araucana hen, CC BY-SA, via Wikimedia Commons',
    sources: [SRC.cackleColor, SRC.mcmurrayCat, SRC.cackleBreeds],
  },
  {
    id: 'olive',
    name: 'Olive Egger',
    eggColorFamily: 'olive',
    eggColorLabel: 'Olive green',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Often a pea comb; muffs and beard common on Egger types.',
      plumage: 'Copper to mahogany with darker lace; highly variable.',
      body: 'Medium dual-purpose look from blue × dark-brown crosses.',
      legs: 'Slate or willow shanks often travel with the blue-egg side.',
    },
    tagline: 'Blue × dark-brown cross',
    simpleCopy: 'Olive eggs happen when blue-shell genetics meet dark brown pigment — brown over blue reads green. According to Cackle Hatchery, Olive Eggers lay Medium–Large olive green eggs; Koops Coops hatches Olive Eggers weekly.',
    advancedCopy: 'Cackle’s Damerow article: a green shell is blue with a brown coating; dark brown over blue yields olive. “Olive Egger” is a cross description, not a closed breed. Darker brown parents (Marans lines) deepen the olive; lighter brown parents give softer sage.',
    photo: 'images/breed-olive-egger.jpg',
    photoCredit: 'Photo: Easter Egger hen “Gem” (Olive Eggers look similar), CC BY-SA, via Wikimedia Commons',
    sources: [SRC.koopsProcess, SRC.cackleBreeds, SRC.cackleColor, SRC.mcmurray],
  },
  {
    id: 'whiting-true-green',
    name: 'Whiting True Green',
    eggColorFamily: 'olive',
    eggColorLabel: 'Green',
    eggSize: 'Medium to Large',
    henTraits: {
      comb: 'Typically single or pea depending on line.',
      plumage: 'Production hybrid coloring — varies by hatchery line.',
      body: 'Efficient layer type selected for green shells.',
      legs: 'Clean shanks; production-layer proportions.',
    },
    tagline: 'Selected green-egg hybrid',
    simpleCopy: 'Whiting True Greens are selected for consistent green eggs. According to Murray McMurray Hatchery’s 2026 catalog they sit with other tinted/colored egg layers beside Whiting True Blues.',
    advancedCopy: 'Green shells still follow the blue-matrix + brown-bloom stack Cackle describes. Hybrids like Whiting lines will not breed true for egg color the way closed Heritage breeds do — McMurray notes similar caveats for production crosses.',
    photo: null,
    photoCredit: null,
    sources: [SRC.mcmurrayCat, SRC.cackleColor, SRC.mcmurray],
  },
  {
    id: 'olive-marans-cross',
    name: 'Dark Olive Egger (Marans cross)',
    eggColorFamily: 'olive',
    eggColorLabel: 'Deep olive',
    eggSize: 'Large',
    henTraits: {
      comb: 'Pea or single; often muffed when Ameraucana blood is present.',
      plumage: 'Darker dual-purpose mix — black, copper, or laced looks common.',
      body: 'Heavier than light Eggers when Marans parents contribute mass.',
      legs: 'Feathered or clean depending on Marans parent type.',
    },
    tagline: 'Deep olive specialty cross',
    simpleCopy: 'Crossing dark Marans with blue layers pushes olive eggs toward a deeper mossy green. According to Cackle’s Damerow article, darker brown pigment over blue deepens olive; Koops Coops offers both Marans and Olive Eggers for that palette.',
    advancedCopy: 'Structurally you still have biliverdin in the matrix plus heavy protoporphyrin on top. Shade still varies hen to hen, so select breeders for the olive you want.',
    photo: null,
    photoCredit: null,
    sources: [SRC.cackleColor, SRC.koopsProcess, SRC.cackleBreeds, SRC.mcmurrayCat],
  },
];

export function getBreedById(id) {
  for (var i = 0; i < BREEDS.length; i++) {
    if (BREEDS[i].id === id) return BREEDS[i];
  }
  return BREEDS[0];
}
